openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /test:
    get:
      responses:
        '200':
          description: OK

  # 認証用のloginアドレス取得
  /auth:
    get:
      tags:
        - user
      summary: google loginへのリダイレクトURL取得
      operationId: auth
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string

  /user:
    post:
      tags:
        - user
      summary: ユーザーの新規作成
      operationId: userId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                gmail_id:
                  type: string
                user_img:
                  type: string
                mail_address:
                  type: string
                user_name:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string

  /user/{user_id}:
    get:
      tags:
        - user
      summary: ユーザー情報の取得
      operationId: userInfo
      parameters:
        - in: path
          name: user_id
          schema:  
            type: string
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_name:
                    type: string
                  user_img:
                    type: string
                  # テーマ達成率
                  theme_achievement:
                    type: number

  /themes:
    get:
      tags:
        - user
      summary: テーマの取得
      operationId: themes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  theme_id: 
                    type: string
                  theme_title:
                    type: string
                  theme_img:
                    type: string
                  # テーマが達成してるかどうか
                  theme_done:
                    type: boolean

  /themes/{theme_id}/chapters:
    get:
      tags:
        - user
      summary: チャプター一覧・シチュエーション一覧の取得
      operationId: chapters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
      parameters:
        - in: path
          name: theme_id
          schema:  
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  chapters:
                    type: array
                    items:
                      type: object
                      properties:
                        chapter_id:
                          type: string
                        chapter_title:
                          type: string
                        chapter_img:
                          type: string
                        situation-levels:
                          type: array
                          items:
                            type: object
                            properties:
                              situation_id:
                                type: string
                              situation_title:
                                type: string
                              # シチュエーションの難易度
                              situation_level:
                                type: integer
                              # シチュエーション達成数
                              situation_achieve:
                                type: integer
                              # シチュエーションが正解したかどうか
                              situation_done:
                                type: boolean
                        extras:
                          type: object
                          properties:
                            extra_situation_id:
                              type: string
                            extra_situation_title:
                              type: string
                            # extraが正解したかどうか
                            extra_situation_done:
                              type: boolean


  /situations/{situation_id}/problems/random:
    get:
      tags:
        - user
      summary: 問題の取得
      operationId: problems
      parameters:
        - in: path
          name: situation_id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                # 問題文
                  problem:
                    type: object
                    properties:
                      problem_id:
                        type: string
                      problem_title:
                        type: string
                      # 問題文
                      problem_text:
                        type: string
                      # 問題に対する解説文
                      problem_explanation:
                        type: string
                      # 選択肢
                      choices:
                        type: array
                        items:
                          type: object
                          properties:
                            choice_id:
                              type: string
                            choice_text:
                              type: string
                            choice_explanation:
                              type: string
                            correct_flag:
                              type: boolean

  /extra-situations/{extra_id}/extra-problems:
    get:
      tags:
        - user
      summary: エクストラ問題の取得
      operationId: problems
      parameters:
        - in: path
          name: extra_situation_id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                # エクストラ問題文
                  extra_problem:
                    type: object
                    properties:
                      extra_problem_id:
                        type: string
                      extra_problem_title:
                        type: string
                      # 問題文
                      extra_problem_text:
                        type: string
                      # 問題に対する解説文
                      extra_problem_explanation:
                        type: string
                      # 選択肢
                      extra_choices:
                        type: array
                        items:
                          type: object
                          properties:
                            extra_choice_id:
                              type: string
                            extra_choice_text:
                              type: string
                            extra_choice_explanation:
                              type: string
                            correct_flag:
                              type: boolean

  /situations/{situation_id}/history:
    post:
      tags:
        - user
      summary: 問題の履歴作成
      operationId: createHistory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                situation_id:
                  type: string
                correct_flag:
                  type: boolean
      responses:
        200:
          description: OK

  /extra-situations/{extra_situation_id}/history:
    post:
      tags:
        - user
      summary: エクストラ問題の履歴作成
      operationId: createExtraHistory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                extra_situation_id:
                  type: string
                correct_flag:
                  type: boolean
      responses:
        200:
          description: OK


